#!/bin/bash

gunzip -c $1 > restore.dmp 

sqlplus / as sysdba <<EOF
  STARTUP FORCE RESTRICT;
  drop user tw08 cascade;
  create user tw08 identified by deploisit08;
  grant dba to tw08;
  GRANT CREATE SESSION TO tw08 WITH ADMIN OPTION;
  exit;
EOF
imp \'/ as sysdba\' FULL=y file=restore.dmp
rm restore.dmp
sqlplus / as sysdba <<EOF
  alter system disable restricted session;
EOF
