#! /bin/bash

######################################################
#      BUREAU INFORMATIQUE TW BECHAR        #
######################################################

su - oracle -c "sqlplus / as sysdba <<< 'exec tw08.save_canevas;' " 1> /dev/null

#export rep=`date '+sauvegardeDu_%y%m%d%a_%H-%M'`
export rep=`date '+sauvegardeDu_%y%m%d'`

su - oracle -c "exp \'/ as sysdba\' FULL=y FILE=$rep"
mv /u01/app/oracle/$rep.dmp  /app/sauvegardesoracle
cd /app/sauvegardesoracle
gzip -f $rep.dmp

echo "################ Backup to NAS ################"
if ! lsscsi | grep QNAP > /dev/null; then
        echo "QNAP NAS was not connected"
        /etc/init.d/iscsi restart > /dev/null
        sleep 1
fi
if ! mountpoint /diskserv2 > /dev/null; then
        echo "NAS parent directory was not mounted"
        mount -a
fi
if [ -d "/diskserv2/oracle" ]; then
        echo "Copying Oracle backups to NAS"
	cp -vu /app/sauvegardesoracle/sauvegardeDu* /diskserv2/oracle/
	find /app/sauvegardesoracle/sauvegardeDu* -type f -mtime +14 -delete
else
        echo "Oracle backup NAS directory does not exist"
fi

