ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED PASSWORD_LIFE_TIME UNLIMITED;

SELECT *
FROM dba_profiles
WHERE profile='DEFAULT';

SELECT *
FROM DBA_USERS
WHERE profile='DEFAULT';

ALTER USER tw08 profile tw_users;
;